### ISSUE TITLE
Include December 2018 data

### ISSUE THREAD

**Issue by DanMan** [maxpoulin64/protondb-api#4]
New reports have been posted to https://github.com/bdefore/protondb-data/tree/master/reports and apparently your script didn't notice.

**Comment by DanMan** [comment]
It appears that it's not fixed yet, because the new reports from Jan 1st (23h ago by now) don't show up in the API yet, or doesn't it check every 30min anymore as the website says?

**Comment by maxpoulin64** [comment]
Update scripts work better when they're +x. Literally the only thing I didn't test 🤦‍♂️

Should be good now! Hopefully that means next month will go smoothly.

**Comment by DanMan** [comment]
It worked this time. :+1:
