### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by DanMan** [maxpoulin64/protondb-api#6]
Compare: https://www.protondb.com/app/449610 with https://protondb.max-p.me/games/449610/reports

The first shows 7 reports and the latter only 5, but the latest report is supposedly 2 months old, so it should be part of the dumps already, shouldn't it? Did something break?

**Comment by maxpoulin64** [comment]
Fixed, the thing was running out of memory. I doubled the memory allocation, but eventually the JSON will be so big it will need to be streamed rather than parsed as a whole.

512MB should hold us for a few more months, hopefully...

**Comment by DanMan** [comment]
Well, he's releasing it in monthly chunks, so aren't you processing them in those chunks, too? I'm not using the full reports.json btw, so if getting rid of that helps, feel free to do so.

**Comment by maxpoulin64** [comment]
No, he's basically only releasing the updated gzipped full reports JSON, not just the new reports or the difference. So I have to load up the whole thing and check the timestamps of every report to see if it's newer and insert them in the database.

It's really like they purposedly dump the database in the most unfriendly way possible so nobody can compete, while also shutting up those that wanted the reports to be open.
