### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by davejab** [maxpoulin64/protondb-api#9]
Probably related to #6 

https://www.protondb.com/app/449610  & https://protondb.max-p.me/games/449610/reports

Seem to be missing ~2 years worth of data.

**Comment by maxpoulin64** [comment]
Sorry for the delay, somehow never got notified for that one.

That is partially correct. I had to bump the memory allocation again (to 1.5GB!!), but the data format also changed quite significantly and needs a complete rewrite of everything at this point.

I've just had another request on reddit to fix it, so I might give it another shot, but it's hard to do without a use case.


What do you use the API for and what kind of data would you like to see?

**Comment by davejab** [comment]
Not a problem.

I'd be happy to contribute if a total re-write is required.

As for use case, I have built an alternative to steam.bravehost.com that includes ProtonDB ratings:
https://www.steamplaydb.uk/

I only really need aggregate scores, but I wanted to avoid scraping ProtonDB directly as I did not want to use a WebDriver. Your API, along with some rough logic to generate an overall rating, fulfilled that need.

**Comment by danielwerg** [comment]
@davejab Can't you just use this endpoint: `https://www.protondb.com/api/v1/reports/summaries/{ID}.json` for your use case?

**Comment by davejab** [comment]
@danielwerg yes, that would be perfect for my use case...where is this documented? How have I not found this already?

**Comment by danielwerg** [comment]
@davejab I had it in old typescript project of mine, can't remember how I found it, so no docs. But here is types I use:
```ts
export type ProtonDBTier = 'pending' | 'borked' | 'bronze' | 'silver' | 'gold' | 'platinum';

export interface IProtonDbGame {
  confidence: 'low' | 'good' | 'strong';
  score: number;
  tier: ProtonDBTier;
  total: number;
  trendingTier: ProtonDBTier;
  bestReportedTier: ProtonDBTier;
}
```

**Comment by davejab** [comment]
Thanks @danielwerg !
@maxpoulin64 I'll close this off
